import { pains, capabilities, industries, faqs } from './content.js';
import { INTENTS } from './conversion.js';

const arrow = '<span aria-hidden="true">↗</span>';
export const chatIcon = '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.7" aria-hidden="true"><path d="M21 11.5a8.4 8.4 0 0 1-.9 3.8 8.5 8.5 0 0 1-7.6 4.7 8.4 8.4 0 0 1-3.8-.9L3 21l1.9-5.7a8.4 8.4 0 0 1-.9-3.8 8.5 8.5 0 0 1 4.7-7.6 8.4 8.4 0 0 1 3.8-.9h.5a8.5 8.5 0 0 1 8 8v.5Z"/><path d="M8 10h8M8 14h5"/></svg>';
const wa = (label, source, style = 'button-primary', intent = '') => `<a class="button ${style}" data-wa="${source}" ${intent ? `data-intent="${intent}"` : ''} target="_blank" rel="noopener noreferrer">${chatIcon}${label}${arrow}</a>`;
const eyebrow = (text) => `<p class="eyebrow">${text}</p>`;

export function header() {
  return `<header class="site-header"><div class="shell header-inner"><a class="brand" href="#main" aria-label="CREATIQ AI Solutions 首页">CREATIQ<span>AI SOLUTIONS</span></a><nav aria-label="主要导航"><a href="#pain">你的 Sales 卡在哪里？</a><a href="#solution">认识 2ndU</a><a href="#review">免费 Sales Review</a></nav>${wa('聊聊你的 Sales', 'header', 'button-outline')}</div></header>`;
}

export function hero() {
  return `<section class="hero shell" aria-labelledby="hero-title"><div class="hero-copy">${eyebrow('CREATIQ MODERN SALES FLOW™')}<h1 id="hero-title">老板，<br>Customer 变了。<br><span class="orange">你的 Sales 呢？</span></h1><p class="hero-sub">不是 Customer 越来越难搞。<br>是你的 Sales 方法，<strong>还停留在以前。</strong></p><p id="angle-copy" class="hero-description">Leads 进来了，却问问就静、报价就消失。<br>让我们帮你把机会，带向下一步。</p><div class="hero-actions">${wa('免费 Check 我的 Sales Flow', 'hero')}<a class="text-link" href="#pain">先看看，哪里可能漏掉 <span aria-hidden="true">↓</span></a></div><p class="fine-print">10–15 分钟 · 先看问题 · 适合才继续</p></div><div class="hero-visual"><img src="./images/sme-boss.webp" width="1536" height="1024" fetchpriority="high" alt="明亮店面里，老板在电脑前查看手机上的客户询问。"><div class="photo-note note-top"><span class="note-label">每天都在发生？</span><strong>“Price 发了。然后呢？”</strong><span>Quotation → 已读 → 没下文</span></div><div class="photo-note note-bottom"><span class="note-index">01 / SALES REALITY</span><strong>Leads 不一定少。<br><em>可能是进来后漏掉。</em></strong></div><span class="vertical-caption">MODERN CUSTOMER. MODERN SALES.</span></div></section>`;
}

export function painSection() {
  return `<section id="pain" class="pain-section section"><div class="shell"><div class="section-heading"><div>${eyebrow('THE SALES LEAK')}<h2>广告把人带进来。<br><span class="teal">Sales Flow，把人留下来。</span></h2></div><p>Boss，这三个画面熟不熟？<br>先看清楚哪里断，才知道该改哪里。</p></div><div class="pain-grid">${pains.map(p=>`<article class="pain-item"><span class="large-number">${p.number}</span><div class="scene-quote">${p.scene}</div><h3>${p.title}</h3><p>${p.body}</p><strong class="takeaway">${p.takeaway}</strong></article>`).join('')}</div><p class="section-end">不是每个没成交的 Lead 都能挽回。<strong>但值得先看：有没有可以做得更好的那一段？</strong></p></div></section>`;
}

export function methodSection() {
  return `<section id="method" class="section shell method-section"><div class="method-visual"><img src="./images/sales-team.webp" width="1536" height="1024" loading="lazy" alt="老板与团队在明亮办公室一起梳理销售流程。"><div class="method-stamp">Same team.<br><strong>Better sales flow.</strong></div></div><div class="method-copy">${eyebrow('先有方法，AI 才有商业价值')}<h2>老板，不用再学<br>一百个 <span class="orange">AI Tool。</span></h2><p class="lead">把你公司会卖的方法，<br><strong>变成每天都能执行的 Sales Process。</strong></p><p>CREATIQ 先跟你梳理 Customer 怎么来、为什么卡住、怎样继续。然后把适合的部分，交给 2ndU 执行。</p><div class="method-contrast"><div><span>以前</span><p>问什么，答什么。<br>没回复，就等。</p></div><div><span>现在</span><p>看懂需求，讲对 Value。<br>有 Context，才有下一步。</p></div></div></div><div class="flow-line" aria-label="Modern Sales Flow 七个步骤">${[['Catch','接住机会'],['Understand','看懂需求'],['Match','讲对 Value'],['Handle','处理顾虑'],['Move','带到下一步'],['Follow','接着跟进'],['Human','真人接手']].map(([a,b],i)=>`<div><span>0${i+1}</span><strong>${a}</strong><small>${b}</small></div>`).join('')}</div></section>`;
}

export function solutionSection() {
  return `<section id="solution" class="solution-section section"><div class="shell"><div class="section-heading"><div>${eyebrow('MEET 2ndU · YOUR AI SALES SYSTEM')}<h2>好 Sales 的方法，<br><span class="teal">不只留在一个人脑里。</span></h2></div><p>CREATIQ 设计 Sales Flow。<br><strong>2ndU 帮你的 Team 执行。</strong><br>从第一句 Enquiry，到值得继续的对话。</p></div><div class="solution-layout"><div class="capabilities">${capabilities.map(c=>`<article><span class="cap-number">${c.number}</span><div><p class="cap-label">${c.label}</p><h3>${c.title}</h3><p>${c.text}</p></div></article>`).join('')}</div><div class="conversation-wrap"><div class="conversation-heading"><span class="product-wordmark">2ndU<span>AI + HUMAN SALES</span></span><span class="demo-label">示范对话</span></div><div class="conversation"><p class="chat-context">场景：教育中心 · 家长咨询</p><p class="bubble customer">你们有适合小学生的英文班吗？</p><p class="bubble sales">有的，我们有小学英文课程。你比较希望孩子加强学校成绩，还是更敢开口讲英文？</p><p class="bubble customer">他不太敢开口。</p><p class="bubble sales">明白，你在意的是开口的信心。可以先安排老师了解孩子的情况，再建议适合的课程。要我帮你联系老师吗？</p><p class="bubble customer">好，可以。</p><div class="handover"><span class="handover-mark" aria-hidden="true">↗</span><div><strong>真人接手，带着 Context。</strong><span>需求：开口信心 · 下一步：老师咨询</span></div></div></div><p class="demo-disclaimer">虚构情境，仅示范销售方法。实际回复与安排须按商家核准的资料和流程配置。</p><a href="#review" data-demo class="text-link">用你的业务，看 2ndU Demo ${arrow}</a></div></div></div></section>`;
}

export function industrySection() {
  return `<section class="section shell industry-section"><div>${eyebrow('BUILT AROUND YOUR BUSINESS')}<h2>成交前，需要先聊一聊？<br><span class="teal">就值得看看你的 Sales Flow。</span></h2></div><div class="industry-grid">${industries.map(([title,text],i)=>`<article><span class="industry-num">0${i+1}</span><h3>${title}</h3><p>${text}</p></article>`).join('')}</div><div class="honest-fit"><strong>也不是每间公司，现在都需要 AI。</strong><p>还没有稳定 Leads、产品与流程还不清楚，或必须由专业人士全程判断？先把基础做好。Review 后，我们会坦白告诉你适不适合。</p></div></section>`;
}

export function reviewSection() {
  return `<section id="review" class="review-section section"><div class="shell review-layout"><div class="review-copy">${eyebrow('FREE SALES FLOW REVIEW')}<h2>先不要买 AI。<br>先看看，<br><span class="orange">你的 Sales 漏在哪里。</span></h2><p class="lead">给我们 <strong>10–15 分钟。</strong><br>一起看你的真实 Sales Flow。</p><ul class="review-list"><li>Leads 怎么来，第一句怎么接？</li><li>Customer 常在哪里不 Reply？</li><li>哪些交给 AI，哪些留给 Human？</li></ul><p>适合 2ndU，我们才继续。<br>现在不适合，我们也直接告诉你。</p>${wa('直接 WhatsApp，聊聊我的情况', 'review', 'button-teal')}<p class="fine-print">免费咨询 · 无需先买 Package</p></div><div class="enquiry-card"><div class="form-intro"><span class="form-step">LET’S TALK SALES</span><h3>从你最想改善的一件事开始。</h3><p>填好后，可预览信息并带到 WhatsApp。</p></div><form id="enquiry-form" novalidate><div class="field-row"><label for="name">怎么称呼你？ <span aria-hidden="true">*</span><input id="name" name="name" required maxlength="80" autocomplete="name" placeholder="你的名字" aria-describedby="name-error"><span id="name-error" class="field-error"></span></label><label for="phone">WhatsApp 号码 <span aria-hidden="true">*</span><input id="phone" name="phone" required type="tel" maxlength="32" autocomplete="tel" placeholder="+60 12 345 6789" aria-describedby="phone-error"><span id="phone-error" class="field-error"></span></label></div><label for="company">公司名称 <span class="optional">选填</span><input id="company" name="company" maxlength="120" autocomplete="organization" placeholder="你的公司 / 品牌"></label><label for="intent">我想先<select id="intent" name="intent">${INTENTS.map(i=>`<option>${i}</option>`).join('')}</select></label><label for="problem">你最想改善什么？ <span class="optional">选填</span><textarea id="problem" name="problem" rows="3" maxlength="800" placeholder="例如：报价后经常没下文，Follow Up 也没有固定做法。"></textarea></label><p class="privacy-note">资料只用于这次咨询。网页不会储存你的联络资料；点击 WhatsApp 并发送后，对方才会收到。</p><button class="button button-primary form-submit" type="submit">准备我的 WhatsApp 信息 ${arrow}</button><p id="form-status" role="status" class="form-status"></p></form><div id="message-ready" hidden><h3 id="ready-heading" tabindex="-1">信息准备好了。</h3><p>还未发送。请打开 WhatsApp，检查内容后按 Send。</p><pre id="message-preview"></pre><a id="send-whatsapp" class="button button-teal" target="_blank" rel="noopener noreferrer">${chatIcon}打开 WhatsApp ${arrow}</a><button id="edit-message" class="text-link" type="button">返回修改</button><p class="fine-print">WhatsApp 没打开？可复制上方信息，发送至 +60 16-228 2431。</p></div></div></div></section>`;
}

export function faqSection() {
  return `<section id="faq" class="section shell faq-section"><div>${eyebrow('先讲清楚，再决定')}<h2>Boss，你可能<br>还想问这些。</h2></div><div class="faq-list">${faqs.map(([q,a],i)=>`<details data-faq="${i}"><summary>${q}<span aria-hidden="true">+</span></summary><p>${a}</p></details>`).join('')}</div></section>`;
}

export function footer() {
  return `<footer class="site-footer"><div class="shell footer-inner"><a class="brand" href="#main">CREATIQ<span>AI SOLUTIONS</span></a><p>Modern Customer. Modern Sales.<br><span>2ndU · AI + Human Sales System</span></p><a href="#review">先 Check，再决定。 ${arrow}</a></div><div class="shell footer-bottom"><span>© ${new Date().getFullYear()} CREATIQ AI Solutions</span><span>人物图片为 AI 生成的情境示意，非客户案例。</span></div></footer><aside class="floating-contact" aria-label="随时联系 CREATIQ">${wa('WhatsApp 聊一聊', 'floating', 'button-teal')}</aside>`;
}
